language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t vpstudent/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vpstudent/docker-react npm run test  

